apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: assignment1
  template:
    metadata:
      labels:
        app: assignment1
    spec:
      containers:
      - name: assignment1
        image: public.ecr.aws/v1e7r2t4/assignment1:latest
        ports:
        - containerPort: 8080
